package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCargosPrestamo generated by hbm2java
 */
@Entity
@Table(name="t_cargos_prestamo"
    ,schema="public"
)
public class TCargosPrestamo  implements java.io.Serializable {


     private String idcargosprestamo;
     private TCargosAdmin TCargosAdmin;
     private TRegistroPrestamo TRegistroPrestamo;
     private String descripcion;
     private BigDecimal monto;
     private BigDecimal montoPagado;
     private String estado;
     private Date fd;

    public TCargosPrestamo() {
    }

	
    public TCargosPrestamo(String idcargosprestamo, TCargosAdmin TCargosAdmin, TRegistroPrestamo TRegistroPrestamo, String descripcion) {
        this.idcargosprestamo = idcargosprestamo;
        this.TCargosAdmin = TCargosAdmin;
        this.TRegistroPrestamo = TRegistroPrestamo;
        this.descripcion = descripcion;
    }
    public TCargosPrestamo(String idcargosprestamo, TCargosAdmin TCargosAdmin, TRegistroPrestamo TRegistroPrestamo, String descripcion, BigDecimal monto, BigDecimal montoPagado, String estado, Date fd) {
       this.idcargosprestamo = idcargosprestamo;
       this.TCargosAdmin = TCargosAdmin;
       this.TRegistroPrestamo = TRegistroPrestamo;
       this.descripcion = descripcion;
       this.monto = monto;
       this.montoPagado = montoPagado;
       this.estado = estado;
       this.fd = fd;
    }
   
     @Id 
    
    @Column(name="idcargosprestamo", unique=true, nullable=false, length=41)
    public String getIdcargosprestamo() {
        return this.idcargosprestamo;
    }
    
    public void setIdcargosprestamo(String idcargosprestamo) {
        this.idcargosprestamo = idcargosprestamo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcargosadmin", nullable=false)
    public TCargosAdmin getTCargosAdmin() {
        return this.TCargosAdmin;
    }
    
    public void setTCargosAdmin(TCargosAdmin TCargosAdmin) {
        this.TCargosAdmin = TCargosAdmin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregistroprestamo", nullable=false)
    public TRegistroPrestamo getTRegistroPrestamo() {
        return this.TRegistroPrestamo;
    }
    
    public void setTRegistroPrestamo(TRegistroPrestamo TRegistroPrestamo) {
        this.TRegistroPrestamo = TRegistroPrestamo;
    }
    
    @Column(name="descripcion", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="monto", precision=20)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    
    @Column(name="monto_pagado", precision=20)
    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    
    @Column(name="estado", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fd", length=29)
    public Date getFd() {
        return this.fd;
    }
    
    public void setFd(Date fd) {
        this.fd = fd;
    }




}


