package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TCertificado generated by hbm2java
 */
@Entity
@Table(name="t_certificado"
    ,schema="public"
)
public class TCertificado  implements java.io.Serializable {


     private String idcertificado;
     private TRegistroDepositoRetiro TRegistroDepositoRetiro;
     private String fecha;
     private String numCertificado;
     private String dniRuc;
     private String nombre;
     private String nombreRep;
     private String descripcion;
     private String estado;
     private String tipo;

    public TCertificado() {
    }

	
    public TCertificado(String idcertificado, TRegistroDepositoRetiro TRegistroDepositoRetiro) {
        this.idcertificado = idcertificado;
        this.TRegistroDepositoRetiro = TRegistroDepositoRetiro;
    }
    public TCertificado(String idcertificado, TRegistroDepositoRetiro TRegistroDepositoRetiro, String fecha, String numCertificado, String dniRuc, String nombre, String nombreRep, String descripcion, String estado, String tipo) {
       this.idcertificado = idcertificado;
       this.TRegistroDepositoRetiro = TRegistroDepositoRetiro;
       this.fecha = fecha;
       this.numCertificado = numCertificado;
       this.dniRuc = dniRuc;
       this.nombre = nombre;
       this.nombreRep = nombreRep;
       this.descripcion = descripcion;
       this.estado = estado;
       this.tipo = tipo;
    }
   
     @Id 
    
    @Column(name="idcertificado", unique=true, nullable=false, length=41)
    public String getIdcertificado() {
        return this.idcertificado;
    }
    
    public void setIdcertificado(String idcertificado) {
        this.idcertificado = idcertificado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddepositoretiro", nullable=false)
    public TRegistroDepositoRetiro getTRegistroDepositoRetiro() {
        return this.TRegistroDepositoRetiro;
    }
    
    public void setTRegistroDepositoRetiro(TRegistroDepositoRetiro TRegistroDepositoRetiro) {
        this.TRegistroDepositoRetiro = TRegistroDepositoRetiro;
    }
    
    @Column(name="fecha", length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="num_certificado", length=40)
    public String getNumCertificado() {
        return this.numCertificado;
    }
    
    public void setNumCertificado(String numCertificado) {
        this.numCertificado = numCertificado;
    }
    
    @Column(name="dni_ruc", length=20)
    public String getDniRuc() {
        return this.dniRuc;
    }
    
    public void setDniRuc(String dniRuc) {
        this.dniRuc = dniRuc;
    }
    
    @Column(name="nombre", length=120)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="nombre_rep", length=100)
    public String getNombreRep() {
        return this.nombreRep;
    }
    
    public void setNombreRep(String nombreRep) {
        this.nombreRep = nombreRep;
    }
    
    @Column(name="descripcion", length=4000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="estado", length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="tipo", length=20)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


