package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TCuentaPersona generated by hbm2java
 */
@Entity
@Table(name="t_cuenta_persona"
    ,schema="public"
)
public class TCuentaPersona  implements java.io.Serializable {


     private String idcuentapersona;
     private TTipoCuenta TTipoCuenta;
     private TPersona TPersona;
     private TMoneda TMoneda;
     private String numCta;
     private String fecha;
     private String estado;
     private String observaciones;
     private String ipUser;
     private String idUser;
     private String dateUser;
     private BigDecimal interes;
     private BigDecimal saldo;
     private BigDecimal saldoSinInteres;
     private String fechaActualizacion;
     private String fechaCap;
     private Set TDetalleIntereseses = new HashSet(0);
     private Set TDetalleCuentaPersonas = new HashSet(0);
     private Set TSobregiros = new HashSet(0);
     private Set TRegistroPrestamos = new HashSet(0);
     private Set THistorialCuentaPersonas = new HashSet(0);
     private Set TRegistroDepositoRetiros = new HashSet(0);

    public TCuentaPersona() {
    }

	
    public TCuentaPersona(String idcuentapersona, TTipoCuenta TTipoCuenta, TPersona TPersona, TMoneda TMoneda, String numCta, String fecha, String estado, String ipUser, String idUser, String dateUser) {
        this.idcuentapersona = idcuentapersona;
        this.TTipoCuenta = TTipoCuenta;
        this.TPersona = TPersona;
        this.TMoneda = TMoneda;
        this.numCta = numCta;
        this.fecha = fecha;
        this.estado = estado;
        this.ipUser = ipUser;
        this.idUser = idUser;
        this.dateUser = dateUser;
    }
    public TCuentaPersona(String idcuentapersona, TTipoCuenta TTipoCuenta, TPersona TPersona, TMoneda TMoneda, String numCta, String fecha, String estado, String observaciones, String ipUser, String idUser, String dateUser, BigDecimal interes, BigDecimal saldo, BigDecimal saldoSinInteres, String fechaActualizacion, String fechaCap, Set TDetalleIntereseses, Set TDetalleCuentaPersonas, Set TSobregiros, Set TRegistroPrestamos, Set THistorialCuentaPersonas, Set TRegistroDepositoRetiros) {
       this.idcuentapersona = idcuentapersona;
       this.TTipoCuenta = TTipoCuenta;
       this.TPersona = TPersona;
       this.TMoneda = TMoneda;
       this.numCta = numCta;
       this.fecha = fecha;
       this.estado = estado;
       this.observaciones = observaciones;
       this.ipUser = ipUser;
       this.idUser = idUser;
       this.dateUser = dateUser;
       this.interes = interes;
       this.saldo = saldo;
       this.saldoSinInteres = saldoSinInteres;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaCap = fechaCap;
       this.TDetalleIntereseses = TDetalleIntereseses;
       this.TDetalleCuentaPersonas = TDetalleCuentaPersonas;
       this.TSobregiros = TSobregiros;
       this.TRegistroPrestamos = TRegistroPrestamos;
       this.THistorialCuentaPersonas = THistorialCuentaPersonas;
       this.TRegistroDepositoRetiros = TRegistroDepositoRetiros;
    }
   
     @Id 
    
    @Column(name="idcuentapersona", unique=true, nullable=false, length=41)
    public String getIdcuentapersona() {
        return this.idcuentapersona;
    }
    
    public void setIdcuentapersona(String idcuentapersona) {
        this.idcuentapersona = idcuentapersona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_cuenta", nullable=false)
    public TTipoCuenta getTTipoCuenta() {
        return this.TTipoCuenta;
    }
    
    public void setTTipoCuenta(TTipoCuenta TTipoCuenta) {
        this.TTipoCuenta = TTipoCuenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user_pk", nullable=false)
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_moneda", nullable=false)
    public TMoneda getTMoneda() {
        return this.TMoneda;
    }
    
    public void setTMoneda(TMoneda TMoneda) {
        this.TMoneda = TMoneda;
    }
    
    @Column(name="num_cta", nullable=false, length=50)
    public String getNumCta() {
        return this.numCta;
    }
    
    public void setNumCta(String numCta) {
        this.numCta = numCta;
    }
    
    @Column(name="fecha", nullable=false, length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="observaciones", length=500)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
    
    @Column(name="interes", precision=20)
    public BigDecimal getInteres() {
        return this.interes;
    }
    
    public void setInteres(BigDecimal interes) {
        this.interes = interes;
    }
    
    @Column(name="saldo", precision=20, scale=4)
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    
    @Column(name="saldo_sin_interes", precision=20)
    public BigDecimal getSaldoSinInteres() {
        return this.saldoSinInteres;
    }
    
    public void setSaldoSinInteres(BigDecimal saldoSinInteres) {
        this.saldoSinInteres = saldoSinInteres;
    }
    
    @Column(name="fecha_actualizacion", length=50)
    public String getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(String fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    
    @Column(name="fecha_cap", length=50)
    public String getFechaCap() {
        return this.fechaCap;
    }
    
    public void setFechaCap(String fechaCap) {
        this.fechaCap = fechaCap;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TCuentaPersona")
    public Set getTDetalleIntereseses() {
        return this.TDetalleIntereseses;
    }
    
    public void setTDetalleIntereseses(Set TDetalleIntereseses) {
        this.TDetalleIntereseses = TDetalleIntereseses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TCuentaPersona")
    public Set getTDetalleCuentaPersonas() {
        return this.TDetalleCuentaPersonas;
    }
    
    public void setTDetalleCuentaPersonas(Set TDetalleCuentaPersonas) {
        this.TDetalleCuentaPersonas = TDetalleCuentaPersonas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TCuentaPersona")
    public Set getTSobregiros() {
        return this.TSobregiros;
    }
    
    public void setTSobregiros(Set TSobregiros) {
        this.TSobregiros = TSobregiros;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TCuentaPersona")
    public Set getTRegistroPrestamos() {
        return this.TRegistroPrestamos;
    }
    
    public void setTRegistroPrestamos(Set TRegistroPrestamos) {
        this.TRegistroPrestamos = TRegistroPrestamos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TCuentaPersona")
    public Set getTHistorialCuentaPersonas() {
        return this.THistorialCuentaPersonas;
    }
    
    public void setTHistorialCuentaPersonas(Set THistorialCuentaPersonas) {
        this.THistorialCuentaPersonas = THistorialCuentaPersonas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TCuentaPersona")
    public Set getTRegistroDepositoRetiros() {
        return this.TRegistroDepositoRetiros;
    }
    
    public void setTRegistroDepositoRetiros(Set TRegistroDepositoRetiros) {
        this.TRegistroDepositoRetiros = TRegistroDepositoRetiros;
    }




}


