package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDetallePrestamo generated by hbm2java
 */
@Entity
@Table(name = "t_detalle_prestamo", schema = "public")
public class TDetallePrestamo implements java.io.Serializable {

    private String iddetalleprestamo;
    private TRegistroPrestamo TRegistroPrestamo;
    private BigDecimal numeroCuota;
    private BigDecimal montoCapital;
    private BigDecimal montoTotal;
    private String fechaPago;
    private BigDecimal interesPrestamo;
    private BigDecimal interesMoratorio;
    private String idUser;
    private String ipUser;
    private String dateUser;
    private String estado;
    private BigDecimal capitalPendiente;
    private BigDecimal interesComp;
    private BigDecimal comision;
    private BigDecimal intSuspendidoItf;
    private BigDecimal mora;
    private BigDecimal cargos;
    private BigDecimal seguro;
    private BigDecimal totalPago;
    private String fechaPagoOp;
    private Integer estadoPago;
    private BigDecimal capitalPagado;
    private BigDecimal interesPagado;
    private BigDecimal moraPagada;
    private BigDecimal cargosPagado;
    private BigDecimal seguroPagado;
    private BigDecimal cuota;
    private BigDecimal descuento;
    private BigDecimal interesEfectivo;
    private BigDecimal capitalAmortizado;
    private BigDecimal amortizacionAnticipada;
    private Set TCobranzas = new HashSet(0);

    public TDetallePrestamo() {
    }

    public TDetallePrestamo(String iddetalleprestamo, TRegistroPrestamo TRegistroPrestamo, BigDecimal numeroCuota, BigDecimal montoCapital, BigDecimal montoTotal, String fechaPago, BigDecimal interesPrestamo, BigDecimal interesMoratorio, String idUser, String ipUser, String dateUser, BigDecimal capitalPendiente) {
        this.iddetalleprestamo = iddetalleprestamo;
        this.TRegistroPrestamo = TRegistroPrestamo;
        this.numeroCuota = numeroCuota;
        this.montoCapital = montoCapital;
        this.montoTotal = montoTotal;
        this.fechaPago = fechaPago;
        this.interesPrestamo = interesPrestamo;
        this.interesMoratorio = interesMoratorio;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
        this.capitalPendiente = capitalPendiente;
    }

    public TDetallePrestamo(String iddetalleprestamo, TRegistroPrestamo TRegistroPrestamo, BigDecimal numeroCuota, BigDecimal montoCapital, BigDecimal montoTotal, String fechaPago, BigDecimal interesPrestamo, BigDecimal interesMoratorio, String idUser, String ipUser, String dateUser, String estado, BigDecimal capitalPendiente, BigDecimal interesComp, BigDecimal comision, BigDecimal intSuspendidoItf, BigDecimal mora, BigDecimal cargos, BigDecimal seguro, BigDecimal totalPago, String fechaPagoOp, Integer estadoPago, BigDecimal capitalPagado, BigDecimal interesPagado, BigDecimal moraPagada, BigDecimal cargosPagado, BigDecimal seguroPagado, BigDecimal cuota, BigDecimal descuento, BigDecimal interesEfectivo, Set TCobranzas) {
        this.iddetalleprestamo = iddetalleprestamo;
        this.TRegistroPrestamo = TRegistroPrestamo;
        this.numeroCuota = numeroCuota;
        this.montoCapital = montoCapital;
        this.montoTotal = montoTotal;
        this.fechaPago = fechaPago;
        this.interesPrestamo = interesPrestamo;
        this.interesMoratorio = interesMoratorio;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
        this.estado = estado;
        this.capitalPendiente = capitalPendiente;
        this.interesComp = interesComp;
        this.comision = comision;
        this.intSuspendidoItf = intSuspendidoItf;
        this.mora = mora;
        this.cargos = cargos;
        this.seguro = seguro;
        this.totalPago = totalPago;
        this.fechaPagoOp = fechaPagoOp;
        this.estadoPago = estadoPago;
        this.capitalPagado = capitalPagado;
        this.interesPagado = interesPagado;
        this.moraPagada = moraPagada;
        this.cargosPagado = cargosPagado;
        this.seguroPagado = seguroPagado;
        this.cuota = cuota;
        this.descuento = descuento;
        this.interesEfectivo = interesEfectivo;
        this.TCobranzas = TCobranzas;
    }

    @Id
    @Column(name = "iddetalleprestamo", unique = true, nullable = false, length = 41)
    public String getIddetalleprestamo() {
        return this.iddetalleprestamo;
    }

    public void setIddetalleprestamo(String iddetalleprestamo) {
        this.iddetalleprestamo = iddetalleprestamo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idprestamo", nullable = false)
    public TRegistroPrestamo getTRegistroPrestamo() {
        return this.TRegistroPrestamo;
    }

    public void setTRegistroPrestamo(TRegistroPrestamo TRegistroPrestamo) {
        this.TRegistroPrestamo = TRegistroPrestamo;
    }

    @Column(name = "numero_cuota", nullable = false, precision = 20, scale = 0)
    public BigDecimal getNumeroCuota() {
        return this.numeroCuota;
    }

    public void setNumeroCuota(BigDecimal numeroCuota) {
        this.numeroCuota = numeroCuota;
    }

    @Column(name = "monto_capital", nullable = false, precision = 20, scale = 4)
    public BigDecimal getMontoCapital() {
        return this.montoCapital;
    }

    public void setMontoCapital(BigDecimal montoCapital) {
        this.montoCapital = montoCapital;
    }

    @Column(name = "monto_total", nullable = false, precision = 20, scale = 4)
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }

    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }

    @Column(name = "fecha_pago", nullable = false, length = 50)
    public String getFechaPago() {
        return this.fechaPago;
    }

    public void setFechaPago(String fechaPago) {
        this.fechaPago = fechaPago;
    }

    @Column(name = "interes_prestamo", nullable = false, precision = 20, scale = 4)
    public BigDecimal getInteresPrestamo() {
        return this.interesPrestamo;
    }

    public void setInteresPrestamo(BigDecimal interesPrestamo) {
        this.interesPrestamo = interesPrestamo;
    }

    @Column(name = "interes_moratorio", nullable = false, precision = 20, scale = 4)
    public BigDecimal getInteresMoratorio() {
        return this.interesMoratorio;
    }

    public void setInteresMoratorio(BigDecimal interesMoratorio) {
        this.interesMoratorio = interesMoratorio;
    }

    @Column(name = "id_user", nullable = false, length = 50)
    public String getIdUser() {
        return this.idUser;
    }

    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    @Column(name = "ip_user", nullable = false, length = 50)
    public String getIpUser() {
        return this.ipUser;
    }

    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }

    @Column(name = "date_user", nullable = false, length = 50)
    public String getDateUser() {
        return this.dateUser;
    }

    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }

    @Column(name = "estado", length = 50)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "capital_pendiente", nullable = false, precision = 20, scale = 4)
    public BigDecimal getCapitalPendiente() {
        return this.capitalPendiente;
    }

    public void setCapitalPendiente(BigDecimal capitalPendiente) {
        this.capitalPendiente = capitalPendiente;
    }

    @Column(name = "interes_comp", precision = 20)
    public BigDecimal getInteresComp() {
        return this.interesComp;
    }

    public void setInteresComp(BigDecimal interesComp) {
        this.interesComp = interesComp;
    }

    @Column(name = "comision", precision = 20)
    public BigDecimal getComision() {
        return this.comision;
    }

    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }

    @Column(name = "int_suspendido_itf", precision = 20)
    public BigDecimal getIntSuspendidoItf() {
        return this.intSuspendidoItf;
    }

    public void setIntSuspendidoItf(BigDecimal intSuspendidoItf) {
        this.intSuspendidoItf = intSuspendidoItf;
    }

    @Column(name = "mora", precision = 20)
    public BigDecimal getMora() {
        return this.mora;
    }

    public void setMora(BigDecimal mora) {
        this.mora = mora;
    }

    @Column(name = "cargos", precision = 20)
    public BigDecimal getCargos() {
        return this.cargos;
    }

    public void setCargos(BigDecimal cargos) {
        this.cargos = cargos;
    }

    @Column(name = "seguro", precision = 20)
    public BigDecimal getSeguro() {
        return this.seguro;
    }

    public void setSeguro(BigDecimal seguro) {
        this.seguro = seguro;
    }

    @Column(name = "total_pago", precision = 20)
    public BigDecimal getTotalPago() {
        return this.totalPago;
    }

    public void setTotalPago(BigDecimal totalPago) {
        this.totalPago = totalPago;
    }

    @Column(name = "fecha_pago_op", length = 50)
    public String getFechaPagoOp() {
        return this.fechaPagoOp;
    }

    public void setFechaPagoOp(String fechaPagoOp) {
        this.fechaPagoOp = fechaPagoOp;
    }

    @Column(name = "estado_pago")
    public Integer getEstadoPago() {
        return this.estadoPago;
    }

    public void setEstadoPago(Integer estadoPago) {
        this.estadoPago = estadoPago;
    }

    @Column(name = "capital_pagado", precision = 20)
    public BigDecimal getCapitalPagado() {
        return this.capitalPagado;
    }

    public void setCapitalPagado(BigDecimal capitalPagado) {
        this.capitalPagado = capitalPagado;
    }

    @Column(name = "interes_pagado", precision = 20)
    public BigDecimal getInteresPagado() {
        return this.interesPagado;
    }

    public void setInteresPagado(BigDecimal interesPagado) {
        this.interesPagado = interesPagado;
    }

    @Column(name = "mora_pagada", precision = 20)
    public BigDecimal getMoraPagada() {
        return this.moraPagada;
    }

    public void setMoraPagada(BigDecimal moraPagada) {
        this.moraPagada = moraPagada;
    }

    @Column(name = "cargos_pagado", precision = 20)
    public BigDecimal getCargosPagado() {
        return this.cargosPagado;
    }

    public void setCargosPagado(BigDecimal cargosPagado) {
        this.cargosPagado = cargosPagado;
    }

    @Column(name = "seguro_pagado", precision = 20)
    public BigDecimal getSeguroPagado() {
        return this.seguroPagado;
    }

    public void setSeguroPagado(BigDecimal seguroPagado) {
        this.seguroPagado = seguroPagado;
    }

    @Column(name = "cuota", precision = 20)
    public BigDecimal getCuota() {
        return this.cuota;
    }

    public void setCuota(BigDecimal cuota) {
        this.cuota = cuota;
    }

    @Column(name = "descuento", precision = 20)
    public BigDecimal getDescuento() {
        return this.descuento;
    }

    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    @Column(name = "interes_efectivo", precision = 20)
    public BigDecimal getInteresEfectivo() {
        return this.interesEfectivo;
    }

    public void setInteresEfectivo(BigDecimal interesEfectivo) {
        this.interesEfectivo = interesEfectivo;
    }

    @Column(name = "capital_amortizado", precision = 20)
    public BigDecimal getCapitalAmortizado() {
        return this.capitalAmortizado;
    }

    public void setCapitalAmortizado(BigDecimal capitalAmortizado) {
        this.capitalAmortizado = capitalAmortizado;
    }

    @Column(name = "amortizacion_anticipada", precision = 20)
    public BigDecimal getAmortizacionAnticipada() {
        return this.amortizacionAnticipada;
    }

    public void setAmortizacionAnticipada(BigDecimal amortizacionAnticipada) {
        this.amortizacionAnticipada = amortizacionAnticipada;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "TDetallePrestamo")
    public Set getTCobranzas() {
        return this.TCobranzas;
    }

    public void setTCobranzas(Set TCobranzas) {
        this.TCobranzas = TCobranzas;
    }
}


