package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDistrito generated by hbm2java
 */
@Entity
@Table(name="t_distrito"
    ,schema="public"
)
public class TDistrito  implements java.io.Serializable {


     private String iddistrito;
     private TProvincia TProvincia;
     private String codigo;
     private String descripcion;
     private Set TFilials = new HashSet(0);

    public TDistrito() {
    }

	
    public TDistrito(String iddistrito, TProvincia TProvincia, String codigo, String descripcion) {
        this.iddistrito = iddistrito;
        this.TProvincia = TProvincia;
        this.codigo = codigo;
        this.descripcion = descripcion;
    }
    public TDistrito(String iddistrito, TProvincia TProvincia, String codigo, String descripcion, Set TFilials) {
       this.iddistrito = iddistrito;
       this.TProvincia = TProvincia;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.TFilials = TFilials;
    }
   
     @Id 
    
    @Column(name="iddistrito", unique=true, nullable=false, length=41)
    public String getIddistrito() {
        return this.iddistrito;
    }
    
    public void setIddistrito(String iddistrito) {
        this.iddistrito = iddistrito;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprovincia", nullable=false)
    public TProvincia getTProvincia() {
        return this.TProvincia;
    }
    
    public void setTProvincia(TProvincia TProvincia) {
        this.TProvincia = TProvincia;
    }
    
    @Column(name="codigo", nullable=false, length=50)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="descripcion", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TDistrito")
    public Set getTFilials() {
        return this.TFilials;
    }
    
    public void setTFilials(Set TFilials) {
        this.TFilials = TFilials;
    }




}


