package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TGarantiaCliente generated by hbm2java
 */
@Entity
@Table(name="t_garantia_cliente"
    ,schema="public"
)
public class TGarantiaCliente  implements java.io.Serializable {


     private String idgarantiacliente;
     private TPersona TPersona;
     private TMoneda TMoneda;
     private TTipoGarantia TTipoGarantia;
     private TRegistroPrestamo TRegistroPrestamo;
     private String descripcion;
     private String fechaContrato;
     private BigDecimal montoValorReposicion;
     private BigDecimal montoValorRealizacion;
     private String fechaTasacion;
     private BigDecimal montoValorComercial;
     private String nombreTasador;
     private String ubicacionGarantia;
     private BigDecimal montoHipoteca;
     private String fichaRegistroPartida;
     private Integer seguro;
     private BigDecimal montoGarantia;
     private BigDecimal montoUtilGarantia;
     private String fecha;
     private Date fd;

    public TGarantiaCliente() {
    }

	
    public TGarantiaCliente(String idgarantiacliente, TPersona TPersona, TMoneda TMoneda, TTipoGarantia TTipoGarantia, TRegistroPrestamo TRegistroPrestamo) {
        this.idgarantiacliente = idgarantiacliente;
        this.TPersona = TPersona;
        this.TMoneda = TMoneda;
        this.TTipoGarantia = TTipoGarantia;
        this.TRegistroPrestamo = TRegistroPrestamo;
    }
    public TGarantiaCliente(String idgarantiacliente, TPersona TPersona, TMoneda TMoneda, TTipoGarantia TTipoGarantia, TRegistroPrestamo TRegistroPrestamo, String descripcion, String fechaContrato, BigDecimal montoValorReposicion, BigDecimal montoValorRealizacion, String fechaTasacion, BigDecimal montoValorComercial, String nombreTasador, String ubicacionGarantia, BigDecimal montoHipoteca, String fichaRegistroPartida, Integer seguro, BigDecimal montoGarantia, BigDecimal montoUtilGarantia, String fecha, Date fd) {
       this.idgarantiacliente = idgarantiacliente;
       this.TPersona = TPersona;
       this.TMoneda = TMoneda;
       this.TTipoGarantia = TTipoGarantia;
       this.TRegistroPrestamo = TRegistroPrestamo;
       this.descripcion = descripcion;
       this.fechaContrato = fechaContrato;
       this.montoValorReposicion = montoValorReposicion;
       this.montoValorRealizacion = montoValorRealizacion;
       this.fechaTasacion = fechaTasacion;
       this.montoValorComercial = montoValorComercial;
       this.nombreTasador = nombreTasador;
       this.ubicacionGarantia = ubicacionGarantia;
       this.montoHipoteca = montoHipoteca;
       this.fichaRegistroPartida = fichaRegistroPartida;
       this.seguro = seguro;
       this.montoGarantia = montoGarantia;
       this.montoUtilGarantia = montoUtilGarantia;
       this.fecha = fecha;
       this.fd = fd;
    }
   
     @Id 
    
    @Column(name="idgarantiacliente", unique=true, nullable=false, length=41)
    public String getIdgarantiacliente() {
        return this.idgarantiacliente;
    }
    
    public void setIdgarantiacliente(String idgarantiacliente) {
        this.idgarantiacliente = idgarantiacliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user_pk", nullable=false)
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_moneda", nullable=false)
    public TMoneda getTMoneda() {
        return this.TMoneda;
    }
    
    public void setTMoneda(TMoneda TMoneda) {
        this.TMoneda = TMoneda;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipogarantia", nullable=false)
    public TTipoGarantia getTTipoGarantia() {
        return this.TTipoGarantia;
    }
    
    public void setTTipoGarantia(TTipoGarantia TTipoGarantia) {
        this.TTipoGarantia = TTipoGarantia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregistroprestamo", nullable=false)
    public TRegistroPrestamo getTRegistroPrestamo() {
        return this.TRegistroPrestamo;
    }
    
    public void setTRegistroPrestamo(TRegistroPrestamo TRegistroPrestamo) {
        this.TRegistroPrestamo = TRegistroPrestamo;
    }
    
    @Column(name="descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="fecha_contrato", length=50)
    public String getFechaContrato() {
        return this.fechaContrato;
    }
    
    public void setFechaContrato(String fechaContrato) {
        this.fechaContrato = fechaContrato;
    }
    
    @Column(name="monto_valor_reposicion", precision=20)
    public BigDecimal getMontoValorReposicion() {
        return this.montoValorReposicion;
    }
    
    public void setMontoValorReposicion(BigDecimal montoValorReposicion) {
        this.montoValorReposicion = montoValorReposicion;
    }
    
    @Column(name="monto_valor_realizacion", precision=20)
    public BigDecimal getMontoValorRealizacion() {
        return this.montoValorRealizacion;
    }
    
    public void setMontoValorRealizacion(BigDecimal montoValorRealizacion) {
        this.montoValorRealizacion = montoValorRealizacion;
    }
    
    @Column(name="fecha_tasacion", length=50)
    public String getFechaTasacion() {
        return this.fechaTasacion;
    }
    
    public void setFechaTasacion(String fechaTasacion) {
        this.fechaTasacion = fechaTasacion;
    }
    
    @Column(name="monto_valor_comercial", precision=20)
    public BigDecimal getMontoValorComercial() {
        return this.montoValorComercial;
    }
    
    public void setMontoValorComercial(BigDecimal montoValorComercial) {
        this.montoValorComercial = montoValorComercial;
    }
    
    @Column(name="nombre_tasador", length=100)
    public String getNombreTasador() {
        return this.nombreTasador;
    }
    
    public void setNombreTasador(String nombreTasador) {
        this.nombreTasador = nombreTasador;
    }
    
    @Column(name="ubicacion_garantia", length=150)
    public String getUbicacionGarantia() {
        return this.ubicacionGarantia;
    }
    
    public void setUbicacionGarantia(String ubicacionGarantia) {
        this.ubicacionGarantia = ubicacionGarantia;
    }
    
    @Column(name="monto_hipoteca", precision=20)
    public BigDecimal getMontoHipoteca() {
        return this.montoHipoteca;
    }
    
    public void setMontoHipoteca(BigDecimal montoHipoteca) {
        this.montoHipoteca = montoHipoteca;
    }
    
    @Column(name="ficha_registro_partida", length=50)
    public String getFichaRegistroPartida() {
        return this.fichaRegistroPartida;
    }
    
    public void setFichaRegistroPartida(String fichaRegistroPartida) {
        this.fichaRegistroPartida = fichaRegistroPartida;
    }
    
    @Column(name="seguro")
    public Integer getSeguro() {
        return this.seguro;
    }
    
    public void setSeguro(Integer seguro) {
        this.seguro = seguro;
    }
    
    @Column(name="monto_garantia", precision=20)
    public BigDecimal getMontoGarantia() {
        return this.montoGarantia;
    }
    
    public void setMontoGarantia(BigDecimal montoGarantia) {
        this.montoGarantia = montoGarantia;
    }
    
    @Column(name="monto_util_garantia", precision=20)
    public BigDecimal getMontoUtilGarantia() {
        return this.montoUtilGarantia;
    }
    
    public void setMontoUtilGarantia(BigDecimal montoUtilGarantia) {
        this.montoUtilGarantia = montoUtilGarantia;
    }
    
    @Column(name="fecha", length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fd", length=29)
    public Date getFd() {
        return this.fd;
    }
    
    public void setFd(Date fd) {
        this.fd = fd;
    }




}


