package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOperacion generated by hbm2java
 */
@Entity
@Table(name="t_operacion"
    ,schema="public"
)
public class TOperacion  implements java.io.Serializable {


     private String idOperacion;
     private TTipoOperacion TTipoOperacion;
     private TPersonaCaja TPersonaCaja;
     private TMoneda TMoneda;
     private String numeroOperacion;
     private String descripcion;
     private String fecha;
     private String estado;
     private String idUser;
     private String ipUser;
     private String dateUser;
     private String fechaExtornacion;
     private String idAdminExtorno;
     private BigDecimal saldofinal;
     private Date fd;
     private BigDecimal saldoFinalSinInteres;
     private Set TRegistroDepositoRetiros = new HashSet(0);
     private Set TCobranzas = new HashSet(0);
     private Set TRegistroCompraVentas = new HashSet(0);
     private Set TRegistroGiros = new HashSet(0);
     private Set TTransferenciaCajas = new HashSet(0);
     private Set TRegistroPrestamos = new HashSet(0);
     private Set TRegistroOtroses = new HashSet(0);

    public TOperacion() {
    }

	
    public TOperacion(String idOperacion, TTipoOperacion TTipoOperacion, TPersonaCaja TPersonaCaja, TMoneda TMoneda, String numeroOperacion, String fecha, String estado, String idUser, String ipUser, String dateUser) {
        this.idOperacion = idOperacion;
        this.TTipoOperacion = TTipoOperacion;
        this.TPersonaCaja = TPersonaCaja;
        this.TMoneda = TMoneda;
        this.numeroOperacion = numeroOperacion;
        this.fecha = fecha;
        this.estado = estado;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
    }
    public TOperacion(String idOperacion, TTipoOperacion TTipoOperacion, TPersonaCaja TPersonaCaja, TMoneda TMoneda, String numeroOperacion, String descripcion, String fecha, String estado, String idUser, String ipUser, String dateUser, String fechaExtornacion, String idAdminExtorno, BigDecimal saldofinal, Date fd, BigDecimal saldoFinalSinInteres, Set TRegistroDepositoRetiros, Set TCobranzas, Set TRegistroCompraVentas, Set TRegistroGiros, Set TTransferenciaCajas, Set TRegistroPrestamos, Set TRegistroOtroses) {
       this.idOperacion = idOperacion;
       this.TTipoOperacion = TTipoOperacion;
       this.TPersonaCaja = TPersonaCaja;
       this.TMoneda = TMoneda;
       this.numeroOperacion = numeroOperacion;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.estado = estado;
       this.idUser = idUser;
       this.ipUser = ipUser;
       this.dateUser = dateUser;
       this.fechaExtornacion = fechaExtornacion;
       this.idAdminExtorno = idAdminExtorno;
       this.saldofinal = saldofinal;
       this.fd = fd;
       this.saldoFinalSinInteres = saldoFinalSinInteres;
       this.TRegistroDepositoRetiros = TRegistroDepositoRetiros;
       this.TCobranzas = TCobranzas;
       this.TRegistroCompraVentas = TRegistroCompraVentas;
       this.TRegistroGiros = TRegistroGiros;
       this.TTransferenciaCajas = TTransferenciaCajas;
       this.TRegistroPrestamos = TRegistroPrestamos;
       this.TRegistroOtroses = TRegistroOtroses;
    }
   
     @Id 
    
    @Column(name="id_operacion", unique=true, nullable=false, length=41)
    public String getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(String idOperacion) {
        this.idOperacion = idOperacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_tipo_operacion", nullable=false)
    public TTipoOperacion getTTipoOperacion() {
        return this.TTipoOperacion;
    }
    
    public void setTTipoOperacion(TTipoOperacion TTipoOperacion) {
        this.TTipoOperacion = TTipoOperacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpersonacaja", nullable=false)
    public TPersonaCaja getTPersonaCaja() {
        return this.TPersonaCaja;
    }
    
    public void setTPersonaCaja(TPersonaCaja TPersonaCaja) {
        this.TPersonaCaja = TPersonaCaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_moneda", nullable=false)
    public TMoneda getTMoneda() {
        return this.TMoneda;
    }
    
    public void setTMoneda(TMoneda TMoneda) {
        this.TMoneda = TMoneda;
    }
    
    @Column(name="numero_operacion", nullable=false, length=50)
    public String getNumeroOperacion() {
        return this.numeroOperacion;
    }
    
    public void setNumeroOperacion(String numeroOperacion) {
        this.numeroOperacion = numeroOperacion;
    }
    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="fecha", nullable=false, length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="estado", nullable=false, length=100)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
    
    @Column(name="fecha_extornacion", length=41)
    public String getFechaExtornacion() {
        return this.fechaExtornacion;
    }
    
    public void setFechaExtornacion(String fechaExtornacion) {
        this.fechaExtornacion = fechaExtornacion;
    }
    
    @Column(name="id_admin_extorno", length=41)
    public String getIdAdminExtorno() {
        return this.idAdminExtorno;
    }
    
    public void setIdAdminExtorno(String idAdminExtorno) {
        this.idAdminExtorno = idAdminExtorno;
    }
    
    @Column(name="saldofinal", precision=20, scale=4)
    public BigDecimal getSaldofinal() {
        return this.saldofinal;
    }
    
    public void setSaldofinal(BigDecimal saldofinal) {
        this.saldofinal = saldofinal;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fd", length=13)
    public Date getFd() {
        return this.fd;
    }
    
    public void setFd(Date fd) {
        this.fd = fd;
    }
    
    @Column(name="saldo_final_sin_interes", precision=20, scale=4)
    public BigDecimal getSaldoFinalSinInteres() {
        return this.saldoFinalSinInteres;
    }
    
    public void setSaldoFinalSinInteres(BigDecimal saldoFinalSinInteres) {
        this.saldoFinalSinInteres = saldoFinalSinInteres;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTRegistroDepositoRetiros() {
        return this.TRegistroDepositoRetiros;
    }
    
    public void setTRegistroDepositoRetiros(Set TRegistroDepositoRetiros) {
        this.TRegistroDepositoRetiros = TRegistroDepositoRetiros;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTCobranzas() {
        return this.TCobranzas;
    }
    
    public void setTCobranzas(Set TCobranzas) {
        this.TCobranzas = TCobranzas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTRegistroCompraVentas() {
        return this.TRegistroCompraVentas;
    }
    
    public void setTRegistroCompraVentas(Set TRegistroCompraVentas) {
        this.TRegistroCompraVentas = TRegistroCompraVentas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTRegistroGiros() {
        return this.TRegistroGiros;
    }
    
    public void setTRegistroGiros(Set TRegistroGiros) {
        this.TRegistroGiros = TRegistroGiros;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTTransferenciaCajas() {
        return this.TTransferenciaCajas;
    }
    
    public void setTTransferenciaCajas(Set TTransferenciaCajas) {
        this.TTransferenciaCajas = TTransferenciaCajas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTRegistroPrestamos() {
        return this.TRegistroPrestamos;
    }
    
    public void setTRegistroPrestamos(Set TRegistroPrestamos) {
        this.TRegistroPrestamos = TRegistroPrestamos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOperacion")
    public Set getTRegistroOtroses() {
        return this.TRegistroOtroses;
    }
    
    public void setTRegistroOtroses(Set TRegistroOtroses) {
        this.TRegistroOtroses = TRegistroOtroses;
    }




}


