package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPatrimonioTransit generated by hbm2java
 */
@Entity
@Table(name="t_patrimonio_transit"
    ,schema="public"
)
public class TPatrimonioTransit  implements java.io.Serializable {


     private String idpatrimonio;
     private TBalancexmoneda TBalancexmoneda;
     private BigDecimal patrimonio;
     private BigDecimal patrimonioActual;
     private String estado;
     private String idUser;
     private String ipUser;
     private String dateUser;
     private String tipoVariacion;
     private BigDecimal activoCajaybanco;
     private BigDecimal activoCuentaxcobrar;
     private BigDecimal pasivo;
     private BigDecimal encaje;
     private BigDecimal PRespaldo;
     private Date fd;

    public TPatrimonioTransit() {
    }

	
    public TPatrimonioTransit(String idpatrimonio, TBalancexmoneda TBalancexmoneda, BigDecimal patrimonio, BigDecimal patrimonioActual, String estado, String idUser, String ipUser, String dateUser) {
        this.idpatrimonio = idpatrimonio;
        this.TBalancexmoneda = TBalancexmoneda;
        this.patrimonio = patrimonio;
        this.patrimonioActual = patrimonioActual;
        this.estado = estado;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
    }
    public TPatrimonioTransit(String idpatrimonio, TBalancexmoneda TBalancexmoneda, BigDecimal patrimonio, BigDecimal patrimonioActual, String estado, String idUser, String ipUser, String dateUser, String tipoVariacion, BigDecimal activoCajaybanco, BigDecimal activoCuentaxcobrar, BigDecimal pasivo, BigDecimal encaje, BigDecimal PRespaldo, Date fd) {
       this.idpatrimonio = idpatrimonio;
       this.TBalancexmoneda = TBalancexmoneda;
       this.patrimonio = patrimonio;
       this.patrimonioActual = patrimonioActual;
       this.estado = estado;
       this.idUser = idUser;
       this.ipUser = ipUser;
       this.dateUser = dateUser;
       this.tipoVariacion = tipoVariacion;
       this.activoCajaybanco = activoCajaybanco;
       this.activoCuentaxcobrar = activoCuentaxcobrar;
       this.pasivo = pasivo;
       this.encaje = encaje;
       this.PRespaldo = PRespaldo;
       this.fd = fd;
    }
   
     @Id 
    
    @Column(name="idpatrimonio", unique=true, nullable=false, length=41)
    public String getIdpatrimonio() {
        return this.idpatrimonio;
    }
    
    public void setIdpatrimonio(String idpatrimonio) {
        this.idpatrimonio = idpatrimonio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbalance", nullable=false)
    public TBalancexmoneda getTBalancexmoneda() {
        return this.TBalancexmoneda;
    }
    
    public void setTBalancexmoneda(TBalancexmoneda TBalancexmoneda) {
        this.TBalancexmoneda = TBalancexmoneda;
    }
    
    @Column(name="patrimonio", nullable=false, precision=20, scale=4)
    public BigDecimal getPatrimonio() {
        return this.patrimonio;
    }
    
    public void setPatrimonio(BigDecimal patrimonio) {
        this.patrimonio = patrimonio;
    }
    
    @Column(name="patrimonio_actual", nullable=false, precision=20, scale=4)
    public BigDecimal getPatrimonioActual() {
        return this.patrimonioActual;
    }
    
    public void setPatrimonioActual(BigDecimal patrimonioActual) {
        this.patrimonioActual = patrimonioActual;
    }
    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
    
    @Column(name="tipo_variacion", length=20)
    public String getTipoVariacion() {
        return this.tipoVariacion;
    }
    
    public void setTipoVariacion(String tipoVariacion) {
        this.tipoVariacion = tipoVariacion;
    }
    
    @Column(name="activo_cajaybanco", precision=20, scale=4)
    public BigDecimal getActivoCajaybanco() {
        return this.activoCajaybanco;
    }
    
    public void setActivoCajaybanco(BigDecimal activoCajaybanco) {
        this.activoCajaybanco = activoCajaybanco;
    }
    
    @Column(name="activo_cuentaxcobrar", precision=20, scale=4)
    public BigDecimal getActivoCuentaxcobrar() {
        return this.activoCuentaxcobrar;
    }
    
    public void setActivoCuentaxcobrar(BigDecimal activoCuentaxcobrar) {
        this.activoCuentaxcobrar = activoCuentaxcobrar;
    }
    
    @Column(name="pasivo", precision=20, scale=4)
    public BigDecimal getPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(BigDecimal pasivo) {
        this.pasivo = pasivo;
    }
    
    @Column(name="encaje", precision=20, scale=4)
    public BigDecimal getEncaje() {
        return this.encaje;
    }
    
    public void setEncaje(BigDecimal encaje) {
        this.encaje = encaje;
    }
    
    @Column(name="p_respaldo", precision=20, scale=4)
    public BigDecimal getPRespaldo() {
        return this.PRespaldo;
    }
    
    public void setPRespaldo(BigDecimal PRespaldo) {
        this.PRespaldo = PRespaldo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fd", length=29)
    public Date getFd() {
        return this.fd;
    }
    
    public void setFd(Date fd) {
        this.fd = fd;
    }




}


