package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPersonaCaja generated by hbm2java
 */
@Entity
@Table(name="t_persona_caja"
    ,schema="public"
)
public class TPersonaCaja  implements java.io.Serializable {


     private String idpersonacaja;
     private TCaja TCaja;
     private TPersona TPersona;
     private String estado;
     private String idUser;
     private String ipUser;
     private String dateUser;
     private Set TRegistroOtroses = new HashSet(0);
     private Set TOperacions = new HashSet(0);

    public TPersonaCaja() {
    }

	
    public TPersonaCaja(String idpersonacaja, TCaja TCaja, TPersona TPersona, String estado, String idUser, String ipUser, String dateUser) {
        this.idpersonacaja = idpersonacaja;
        this.TCaja = TCaja;
        this.TPersona = TPersona;
        this.estado = estado;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
    }
    public TPersonaCaja(String idpersonacaja, TCaja TCaja, TPersona TPersona, String estado, String idUser, String ipUser, String dateUser, Set TRegistroOtroses, Set TOperacions) {
       this.idpersonacaja = idpersonacaja;
       this.TCaja = TCaja;
       this.TPersona = TPersona;
       this.estado = estado;
       this.idUser = idUser;
       this.ipUser = ipUser;
       this.dateUser = dateUser;
       this.TRegistroOtroses = TRegistroOtroses;
       this.TOperacions = TOperacions;
    }
   
     @Id 
    
    @Column(name="idpersonacaja", unique=true, nullable=false, length=41)
    public String getIdpersonacaja() {
        return this.idpersonacaja;
    }
    
    public void setIdpersonacaja(String idpersonacaja) {
        this.idpersonacaja = idpersonacaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_caja", nullable=false)
    public TCaja getTCaja() {
        return this.TCaja;
    }
    
    public void setTCaja(TCaja TCaja) {
        this.TCaja = TCaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user_pk", nullable=false)
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    
    @Column(name="estado", nullable=false, length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersonaCaja")
    public Set getTRegistroOtroses() {
        return this.TRegistroOtroses;
    }
    
    public void setTRegistroOtroses(Set TRegistroOtroses) {
        this.TRegistroOtroses = TRegistroOtroses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersonaCaja")
    public Set getTOperacions() {
        return this.TOperacions;
    }
    
    public void setTOperacions(Set TOperacions) {
        this.TOperacions = TOperacions;
    }




}


