package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPersona generated by hbm2java
 */
@Entity
@Table(name="t_persona"
    ,schema="public"
)
public class TPersona  implements java.io.Serializable {


     private String idUserPk;
     private TCategoriaPersona TCategoriaPersona;
     private String docIdentidad;
     private String nombre;
     private String apellidos;
     private String email;
     private String ubigeo;
     private String telefono;
     private String celular;
     private String urlFoto;
     private String urlFirma;
     private String direccion;
     private String estado;
     private String idUser;
     private String ipUser;
     private String dateUser;
     private String ruc;
     private Set TCuentaPersonas = new HashSet(0);
     private Set TControlTipos = new HashSet(0);
     private Set TCuentaAccesos = new HashSet(0);
     private Set TRegistroGiros = new HashSet(0);
     private Set TPersonaCajas = new HashSet(0);
     private Set TGarantiaClientes = new HashSet(0);

    public TPersona() {
    }

	
    public TPersona(String idUserPk, TCategoriaPersona TCategoriaPersona, String nombre, String apellidos, String estado, String idUser, String ipUser, String dateUser) {
        this.idUserPk = idUserPk;
        this.TCategoriaPersona = TCategoriaPersona;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.estado = estado;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
    }
    public TPersona(String idUserPk, TCategoriaPersona TCategoriaPersona, String docIdentidad, String nombre, String apellidos, String email, String ubigeo, String telefono, String celular, String urlFoto, String urlFirma, String direccion, String estado, String idUser, String ipUser, String dateUser, String ruc, Set TCuentaPersonas, Set TControlTipos, Set TCuentaAccesos, Set TRegistroGiros, Set TPersonaCajas, Set TGarantiaClientes) {
       this.idUserPk = idUserPk;
       this.TCategoriaPersona = TCategoriaPersona;
       this.docIdentidad = docIdentidad;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.ubigeo = ubigeo;
       this.telefono = telefono;
       this.celular = celular;
       this.urlFoto = urlFoto;
       this.urlFirma = urlFirma;
       this.direccion = direccion;
       this.estado = estado;
       this.idUser = idUser;
       this.ipUser = ipUser;
       this.dateUser = dateUser;
       this.ruc = ruc;
       this.TCuentaPersonas = TCuentaPersonas;
       this.TControlTipos = TControlTipos;
       this.TCuentaAccesos = TCuentaAccesos;
       this.TRegistroGiros = TRegistroGiros;
       this.TPersonaCajas = TPersonaCajas;
       this.TGarantiaClientes = TGarantiaClientes;
    }
   
     @Id 
    
    @Column(name="id_user_pk", unique=true, nullable=false, length=50)
    public String getIdUserPk() {
        return this.idUserPk;
    }
    
    public void setIdUserPk(String idUserPk) {
        this.idUserPk = idUserPk;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategoriapersona", nullable=false)
    public TCategoriaPersona getTCategoriaPersona() {
        return this.TCategoriaPersona;
    }
    
    public void setTCategoriaPersona(TCategoriaPersona TCategoriaPersona) {
        this.TCategoriaPersona = TCategoriaPersona;
    }
    
    @Column(name="doc_identidad", length=10)
    public String getDocIdentidad() {
        return this.docIdentidad;
    }
    
    public void setDocIdentidad(String docIdentidad) {
        this.docIdentidad = docIdentidad;
    }
    
    @Column(name="nombre", nullable=false, length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="apellidos", nullable=false, length=60)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="ubigeo", length=10)
    public String getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(String ubigeo) {
        this.ubigeo = ubigeo;
    }
    
    @Column(name="telefono", length=100)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="celular", length=100)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    
    @Column(name="url_foto", length=200)
    public String getUrlFoto() {
        return this.urlFoto;
    }
    
    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }
    
    @Column(name="url_firma", length=200)
    public String getUrlFirma() {
        return this.urlFirma;
    }
    
    public void setUrlFirma(String urlFirma) {
        this.urlFirma = urlFirma;
    }
    
    @Column(name="direccion", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
    
    @Column(name="ruc", length=50)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersona")
    public Set getTCuentaPersonas() {
        return this.TCuentaPersonas;
    }
    
    public void setTCuentaPersonas(Set TCuentaPersonas) {
        this.TCuentaPersonas = TCuentaPersonas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersona")
    public Set getTControlTipos() {
        return this.TControlTipos;
    }
    
    public void setTControlTipos(Set TControlTipos) {
        this.TControlTipos = TControlTipos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersona")
    public Set getTCuentaAccesos() {
        return this.TCuentaAccesos;
    }
    
    public void setTCuentaAccesos(Set TCuentaAccesos) {
        this.TCuentaAccesos = TCuentaAccesos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersona")
    public Set getTRegistroGiros() {
        return this.TRegistroGiros;
    }
    
    public void setTRegistroGiros(Set TRegistroGiros) {
        this.TRegistroGiros = TRegistroGiros;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersona")
    public Set getTPersonaCajas() {
        return this.TPersonaCajas;
    }
    
    public void setTPersonaCajas(Set TPersonaCajas) {
        this.TPersonaCajas = TPersonaCajas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPersona")
    public Set getTGarantiaClientes() {
        return this.TGarantiaClientes;
    }
    
    public void setTGarantiaClientes(Set TGarantiaClientes) {
        this.TGarantiaClientes = TGarantiaClientes;
    }




}


