package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TSesion generated by hbm2java
 */
@Entity
@Table(name="t_sesion"
    ,schema="public"
)
public class TSesion  implements java.io.Serializable {


     private String idsession;
     private TCuentaAcceso TCuentaAcceso;
     private String fecha;
     private String accion;
     private String idUser;
     private String ipUser;
     private String dateUser;

    public TSesion() {
    }

    public TSesion(String idsession, TCuentaAcceso TCuentaAcceso, String fecha, String accion, String idUser, String ipUser, String dateUser) {
       this.idsession = idsession;
       this.TCuentaAcceso = TCuentaAcceso;
       this.fecha = fecha;
       this.accion = accion;
       this.idUser = idUser;
       this.ipUser = ipUser;
       this.dateUser = dateUser;
    }
   
     @Id 
    
    @Column(name="idsession", unique=true, nullable=false, length=41)
    public String getIdsession() {
        return this.idsession;
    }
    
    public void setIdsession(String idsession) {
        this.idsession = idsession;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_acceso", nullable=false)
    public TCuentaAcceso getTCuentaAcceso() {
        return this.TCuentaAcceso;
    }
    
    public void setTCuentaAcceso(TCuentaAcceso TCuentaAcceso) {
        this.TCuentaAcceso = TCuentaAcceso;
    }
    
    @Column(name="fecha", nullable=false, length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="accion", nullable=false, length=50)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="ip_user", nullable=false, length=41)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }




}


