package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TTipoCredito generated by hbm2java
 */
@Entity
@Table(name="t_tipo_credito"
    ,schema="public"
)
public class TTipoCredito  implements java.io.Serializable {


     private String idtipocredito;
     private String nombre;
     private String descripcion;
     private String idUser;
     private String ipUser;
     private String dateUser;
     private String ctaContableCapital;
     private BigDecimal montoMaximo;
     private Integer numeroCuotasMax;
     private BigDecimal tasaInteresMax;
     private int tipoTasaInteres;
     private BigDecimal tasaInteresCompensatorio;
     private Integer tipoTasaIntComp;
     private BigDecimal tasaInteresMoratoria;
     private Integer tipoTasaIntMora;
     private Integer cobrarMora;
     private Integer cobrarInteresCompensatorio;
     private Integer formaCobroIntereses;
     private Integer formaCalculoIntereses;
     private Integer numeroCuotasMin;
     private BigDecimal montoMinimo;
     private BigDecimal tasaInteresMin;
     private Integer diasEntreCuotas;
     private Integer tipoCuota;
     private Integer requiereGarantia;
     private Integer avisoCuota;
     private Integer redondeoCuota;
     private Integer modoCalculoIntereses;
     private Integer modoCalcIntComp;
     private Integer modoCobroIntMora;
     private Integer numMaxReprogramacion;
     private Integer numMaxRefinanciacion;
     private Set TRegistroPrestamos = new HashSet(0);

    public TTipoCredito() {
    }

	
    public TTipoCredito(String idtipocredito, String nombre, String idUser, String ipUser, String dateUser, BigDecimal montoMaximo, int tipoTasaInteres, BigDecimal tasaInteresCompensatorio) {
        this.idtipocredito = idtipocredito;
        this.nombre = nombre;
        this.idUser = idUser;
        this.ipUser = ipUser;
        this.dateUser = dateUser;
        this.montoMaximo = montoMaximo;
        this.tipoTasaInteres = tipoTasaInteres;
        this.tasaInteresCompensatorio = tasaInteresCompensatorio;
    }
    public TTipoCredito(String idtipocredito, String nombre, String descripcion, String idUser, String ipUser, String dateUser, String ctaContableCapital, BigDecimal montoMaximo, Integer numeroCuotasMax, BigDecimal tasaInteresMax, int tipoTasaInteres, BigDecimal tasaInteresCompensatorio, Integer tipoTasaIntComp, BigDecimal tasaInteresMoratoria, Integer tipoTasaIntMora, Integer cobrarMora, Integer cobrarInteresCompensatorio, Integer formaCobroIntereses, Integer formaCalculoIntereses, Integer numeroCuotasMin, BigDecimal montoMinimo, BigDecimal tasaInteresMin, Integer diasEntreCuotas, Integer tipoCuota, Integer requiereGarantia, Integer avisoCuota, Integer redondeoCuota, Integer modoCalculoIntereses, Integer modoCalcIntComp, Integer modoCobroIntMora, Integer numMaxReprogramacion, Integer numMaxRefinanciacion, Set TRegistroPrestamos) {
       this.idtipocredito = idtipocredito;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.idUser = idUser;
       this.ipUser = ipUser;
       this.dateUser = dateUser;
       this.ctaContableCapital = ctaContableCapital;
       this.montoMaximo = montoMaximo;
       this.numeroCuotasMax = numeroCuotasMax;
       this.tasaInteresMax = tasaInteresMax;
       this.tipoTasaInteres = tipoTasaInteres;
       this.tasaInteresCompensatorio = tasaInteresCompensatorio;
       this.tipoTasaIntComp = tipoTasaIntComp;
       this.tasaInteresMoratoria = tasaInteresMoratoria;
       this.tipoTasaIntMora = tipoTasaIntMora;
       this.cobrarMora = cobrarMora;
       this.cobrarInteresCompensatorio = cobrarInteresCompensatorio;
       this.formaCobroIntereses = formaCobroIntereses;
       this.formaCalculoIntereses = formaCalculoIntereses;
       this.numeroCuotasMin = numeroCuotasMin;
       this.montoMinimo = montoMinimo;
       this.tasaInteresMin = tasaInteresMin;
       this.diasEntreCuotas = diasEntreCuotas;
       this.tipoCuota = tipoCuota;
       this.requiereGarantia = requiereGarantia;
       this.avisoCuota = avisoCuota;
       this.redondeoCuota = redondeoCuota;
       this.modoCalculoIntereses = modoCalculoIntereses;
       this.modoCalcIntComp = modoCalcIntComp;
       this.modoCobroIntMora = modoCobroIntMora;
       this.numMaxReprogramacion = numMaxReprogramacion;
       this.numMaxRefinanciacion = numMaxRefinanciacion;
       this.TRegistroPrestamos = TRegistroPrestamos;
    }
   
     @Id 
    
    @Column(name="idtipocredito", unique=true, nullable=false, length=41)
    public String getIdtipocredito() {
        return this.idtipocredito;
    }
    
    public void setIdtipocredito(String idtipocredito) {
        this.idtipocredito = idtipocredito;
    }
    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
    
    @Column(name="cta_contable_capital", length=150)
    public String getCtaContableCapital() {
        return this.ctaContableCapital;
    }
    
    public void setCtaContableCapital(String ctaContableCapital) {
        this.ctaContableCapital = ctaContableCapital;
    }
    
    @Column(name="monto_maximo", nullable=false, precision=20)
    public BigDecimal getMontoMaximo() {
        return this.montoMaximo;
    }
    
    public void setMontoMaximo(BigDecimal montoMaximo) {
        this.montoMaximo = montoMaximo;
    }
    
    @Column(name="numero_cuotas_max")
    public Integer getNumeroCuotasMax() {
        return this.numeroCuotasMax;
    }
    
    public void setNumeroCuotasMax(Integer numeroCuotasMax) {
        this.numeroCuotasMax = numeroCuotasMax;
    }
    
    @Column(name="tasa_interes_max", precision=20, scale=4)
    public BigDecimal getTasaInteresMax() {
        return this.tasaInteresMax;
    }
    
    public void setTasaInteresMax(BigDecimal tasaInteresMax) {
        this.tasaInteresMax = tasaInteresMax;
    }
    
    @Column(name="tipo_tasa_interes", nullable=false)
    public int getTipoTasaInteres() {
        return this.tipoTasaInteres;
    }
    
    public void setTipoTasaInteres(int tipoTasaInteres) {
        this.tipoTasaInteres = tipoTasaInteres;
    }
    
    @Column(name="tasa_interes_compensatorio", nullable=false, precision=20)
    public BigDecimal getTasaInteresCompensatorio() {
        return this.tasaInteresCompensatorio;
    }
    
    public void setTasaInteresCompensatorio(BigDecimal tasaInteresCompensatorio) {
        this.tasaInteresCompensatorio = tasaInteresCompensatorio;
    }
    
    @Column(name="tipo_tasa_int_comp")
    public Integer getTipoTasaIntComp() {
        return this.tipoTasaIntComp;
    }
    
    public void setTipoTasaIntComp(Integer tipoTasaIntComp) {
        this.tipoTasaIntComp = tipoTasaIntComp;
    }
    
    @Column(name="tasa_interes_moratoria", precision=20, scale=4)
    public BigDecimal getTasaInteresMoratoria() {
        return this.tasaInteresMoratoria;
    }
    
    public void setTasaInteresMoratoria(BigDecimal tasaInteresMoratoria) {
        this.tasaInteresMoratoria = tasaInteresMoratoria;
    }
    
    @Column(name="tipo_tasa_int_mora")
    public Integer getTipoTasaIntMora() {
        return this.tipoTasaIntMora;
    }
    
    public void setTipoTasaIntMora(Integer tipoTasaIntMora) {
        this.tipoTasaIntMora = tipoTasaIntMora;
    }
    
    @Column(name="cobrar_mora")
    public Integer getCobrarMora() {
        return this.cobrarMora;
    }
    
    public void setCobrarMora(Integer cobrarMora) {
        this.cobrarMora = cobrarMora;
    }
    
    @Column(name="cobrar_interes_compensatorio")
    public Integer getCobrarInteresCompensatorio() {
        return this.cobrarInteresCompensatorio;
    }
    
    public void setCobrarInteresCompensatorio(Integer cobrarInteresCompensatorio) {
        this.cobrarInteresCompensatorio = cobrarInteresCompensatorio;
    }
    
    @Column(name="forma_cobro_intereses")
    public Integer getFormaCobroIntereses() {
        return this.formaCobroIntereses;
    }
    
    public void setFormaCobroIntereses(Integer formaCobroIntereses) {
        this.formaCobroIntereses = formaCobroIntereses;
    }
    
    @Column(name="forma_calculo_intereses")
    public Integer getFormaCalculoIntereses() {
        return this.formaCalculoIntereses;
    }
    
    public void setFormaCalculoIntereses(Integer formaCalculoIntereses) {
        this.formaCalculoIntereses = formaCalculoIntereses;
    }
    
    @Column(name="numero_cuotas_min")
    public Integer getNumeroCuotasMin() {
        return this.numeroCuotasMin;
    }
    
    public void setNumeroCuotasMin(Integer numeroCuotasMin) {
        this.numeroCuotasMin = numeroCuotasMin;
    }
    
    @Column(name="monto_minimo", precision=20)
    public BigDecimal getMontoMinimo() {
        return this.montoMinimo;
    }
    
    public void setMontoMinimo(BigDecimal montoMinimo) {
        this.montoMinimo = montoMinimo;
    }
    
    @Column(name="tasa_interes_min", precision=20, scale=4)
    public BigDecimal getTasaInteresMin() {
        return this.tasaInteresMin;
    }
    
    public void setTasaInteresMin(BigDecimal tasaInteresMin) {
        this.tasaInteresMin = tasaInteresMin;
    }
    
    @Column(name="dias_entre_cuotas")
    public Integer getDiasEntreCuotas() {
        return this.diasEntreCuotas;
    }
    
    public void setDiasEntreCuotas(Integer diasEntreCuotas) {
        this.diasEntreCuotas = diasEntreCuotas;
    }
    
    @Column(name="tipo_cuota")
    public Integer getTipoCuota() {
        return this.tipoCuota;
    }
    
    public void setTipoCuota(Integer tipoCuota) {
        this.tipoCuota = tipoCuota;
    }
    
    @Column(name="requiere_garantia")
    public Integer getRequiereGarantia() {
        return this.requiereGarantia;
    }
    
    public void setRequiereGarantia(Integer requiereGarantia) {
        this.requiereGarantia = requiereGarantia;
    }
    
    @Column(name="aviso_cuota")
    public Integer getAvisoCuota() {
        return this.avisoCuota;
    }
    
    public void setAvisoCuota(Integer avisoCuota) {
        this.avisoCuota = avisoCuota;
    }
    
    @Column(name="redondeo_cuota")
    public Integer getRedondeoCuota() {
        return this.redondeoCuota;
    }
    
    public void setRedondeoCuota(Integer redondeoCuota) {
        this.redondeoCuota = redondeoCuota;
    }
    
    @Column(name="modo_calculo_intereses")
    public Integer getModoCalculoIntereses() {
        return this.modoCalculoIntereses;
    }
    
    public void setModoCalculoIntereses(Integer modoCalculoIntereses) {
        this.modoCalculoIntereses = modoCalculoIntereses;
    }
    
    @Column(name="modo_calc_int_comp")
    public Integer getModoCalcIntComp() {
        return this.modoCalcIntComp;
    }
    
    public void setModoCalcIntComp(Integer modoCalcIntComp) {
        this.modoCalcIntComp = modoCalcIntComp;
    }
    
    @Column(name="modo_cobro_int_mora")
    public Integer getModoCobroIntMora() {
        return this.modoCobroIntMora;
    }
    
    public void setModoCobroIntMora(Integer modoCobroIntMora) {
        this.modoCobroIntMora = modoCobroIntMora;
    }
    
    @Column(name="num_max_reprogramacion")
    public Integer getNumMaxReprogramacion() {
        return this.numMaxReprogramacion;
    }
    
    public void setNumMaxReprogramacion(Integer numMaxReprogramacion) {
        this.numMaxReprogramacion = numMaxReprogramacion;
    }
    
    @Column(name="num_max_refinanciacion")
    public Integer getNumMaxRefinanciacion() {
        return this.numMaxRefinanciacion;
    }
    
    public void setNumMaxRefinanciacion(Integer numMaxRefinanciacion) {
        this.numMaxRefinanciacion = numMaxRefinanciacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TTipoCredito")
    public Set getTRegistroPrestamos() {
        return this.TRegistroPrestamos;
    }
    
    public void setTRegistroPrestamos(Set TRegistroPrestamos) {
        this.TRegistroPrestamos = TRegistroPrestamos;
    }




}


