package org.finance.bank.bean;
// Generated 07/01/2014 06:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TTransferenciaCaja generated by hbm2java
 */
@Entity
@Table(name="t_transferencia_caja"
    ,schema="public"
)
public class TTransferenciaCaja  implements java.io.Serializable {


     private String idtransferenciacaja;
     private TCaja TCaja;
     private TOperacion TOperacion;
     private String fecha;
     private BigDecimal monto;
     private String descripcion;
     private String tipo;
     private String codCajaDestino;
     private String ipUser;
     private String idUser;
     private String dateUser;
     private String idOperacion;
     private String estado;
     private String idope;

    public TTransferenciaCaja() {
    }

	
    public TTransferenciaCaja(String idtransferenciacaja, TCaja TCaja, TOperacion TOperacion, String fecha, BigDecimal monto, String tipo, String codCajaDestino, String ipUser, String idUser, String dateUser, String idOperacion) {
        this.idtransferenciacaja = idtransferenciacaja;
        this.TCaja = TCaja;
        this.TOperacion = TOperacion;
        this.fecha = fecha;
        this.monto = monto;
        this.tipo = tipo;
        this.codCajaDestino = codCajaDestino;
        this.ipUser = ipUser;
        this.idUser = idUser;
        this.dateUser = dateUser;
        this.idOperacion = idOperacion;
    }
    public TTransferenciaCaja(String idtransferenciacaja, TCaja TCaja, TOperacion TOperacion, String fecha, BigDecimal monto, String descripcion, String tipo, String codCajaDestino, String ipUser, String idUser, String dateUser, String idOperacion, String estado, String idope) {
       this.idtransferenciacaja = idtransferenciacaja;
       this.TCaja = TCaja;
       this.TOperacion = TOperacion;
       this.fecha = fecha;
       this.monto = monto;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.codCajaDestino = codCajaDestino;
       this.ipUser = ipUser;
       this.idUser = idUser;
       this.dateUser = dateUser;
       this.idOperacion = idOperacion;
       this.estado = estado;
       this.idope = idope;
    }
   
     @Id 
    
    @Column(name="idtransferenciacaja", unique=true, nullable=false, length=41)
    public String getIdtransferenciacaja() {
        return this.idtransferenciacaja;
    }
    
    public void setIdtransferenciacaja(String idtransferenciacaja) {
        this.idtransferenciacaja = idtransferenciacaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_caja", nullable=false)
    public TCaja getTCaja() {
        return this.TCaja;
    }
    
    public void setTCaja(TCaja TCaja) {
        this.TCaja = TCaja;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_moneda", nullable=false)
    public TOperacion getTOperacion() {
        return this.TOperacion;
    }
    
    public void setTOperacion(TOperacion TOperacion) {
        this.TOperacion = TOperacion;
    }
    
    @Column(name="fecha", nullable=false, length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="monto", nullable=false, precision=20)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    
    @Column(name="descripcion", length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="tipo", nullable=false, length=20)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="cod_caja_destino", nullable=false, length=10)
    public String getCodCajaDestino() {
        return this.codCajaDestino;
    }
    
    public void setCodCajaDestino(String codCajaDestino) {
        this.codCajaDestino = codCajaDestino;
    }
    
    @Column(name="ip_user", nullable=false, length=50)
    public String getIpUser() {
        return this.ipUser;
    }
    
    public void setIpUser(String ipUser) {
        this.ipUser = ipUser;
    }
    
    @Column(name="id_user", nullable=false, length=50)
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    
    @Column(name="date_user", nullable=false, length=50)
    public String getDateUser() {
        return this.dateUser;
    }
    
    public void setDateUser(String dateUser) {
        this.dateUser = dateUser;
    }
    
    @Column(name="id_operacion", nullable=false, length=41)
    public String getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(String idOperacion) {
        this.idOperacion = idOperacion;
    }
    
    @Column(name="estado", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="idope", length=41)
    public String getIdope() {
        return this.idope;
    }
    
    public void setIdope(String idope) {
        this.idope = idope;
    }




}


