/*
INSERT INTO FINANCEBANK.T_CATEGORIA_PERSONA (IDCATEGORIAPERSONA, DESCRIPCION) VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'NATURAL');
INSERT INTO FINANCEBANK.T_CATEGORIA_PERSONA (IDCATEGORIAPERSONA, DESCRIPCION) VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'JURIDICA');


INSERT INTO FINANCEBANK.T_PERSONA (ID_USER_PK, DOC_IDENTIDAD, NOMBRE, APELLIDOS, EMAIL, UBIGEO, TELEFONO, CELULAR, URL_FOTO, URL_FIRMA, DIRECCION, ESTADO, ID_USER, IP_USER, DATE_USER, IDCATEGORIAPERSONA, RUC)
        VALUES ('12345678','DNI', 'ADMIN', 'ADMIN', NULL, '1234567890', NULL, NULL, NULL, NULL, NULL, 'ACTIVO', 'IDUSER', 'IP', 'DATE', '20100226175816694292','RUC');

INSERT INTO FINANCEBANK.T_CUENTA_ACCESO (ID_ACCESO, LOGIN, CONTRASENIA, ESTADO, ID_USER, IP_USER, DATE_USER, ID_USER_PK)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'ADMIN', 'ADMIN1', 'ACTIVO', 'ID', 'IP', 'DATE', '12345678');

INSERT INTO FINANCEBANK.T_TIPO_PERSONA (IDTIPOPERSONA, DESCRIPCION, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'ROL_ADMINISTRADOR', 'ID', 'IP', 'DATE')

INSERT INTO FINANCEBANK.T_CONTROL_TIPO (IDCONTROLTIPO, ID_USER_PK, IDTIPOPERSONA, ID_USER, IP_USER, DATE_USER, ESTADO)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), '12345678', '20100301092857621846', 'ID', 'IP', 'DATE', 'ACTIVO')

INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'),'CAMBIO DE MONEDA', 'cambiomoneda', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'),'GIROS', 'giros', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'COBRO DE GIROS','cobrogiros', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'),'DEPOSITOS / RETIROS', 'depositosretiros', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'NUEVA CUENTA','nuevacuenta', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'PRESTAMOS','prestamos', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'COBRANZAS','cobranzas', 'ID', 'IP', 'DATE');
INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'),'GRUPOS / MODULOS', 'managermodulo', 'ID', 'IP', 'DATE');

INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'ADMINISTRAR USUARIOS','manageruser', 'ID', 'IP', 'DATE');


INSERT INTO FINANCEBANK.T_MODULO (IDMODULO, DESCRIPCION, URL, ID_USER, IP_USER, DATE_USER)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'CAJA','managercaja', 'ID', 'IP', 'DATE');
 INICIANDO VALORES DE LA EMPRESA  PATRIMONIO, ACTIVO Y PASIVOS


INSERT INTO FINANCEBANK.T_CONTROL_MODULO (IDCONTROLMODULO, IDMODULO, IDTIPOPERSONA, ID_USER, IP_USER, DATE_USER, ESTADO) VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), '20100310182800834663', '20100305084505705899', 'ID', 'IP', 'DATE', '1');

INSERT INTO FINANCEBANK.T_BALANCEXMONEDA (IDBALANCE, ACTIVO_CAJAYBANCO, ACTIVO_CUENTAXCOBRAR, PASIVO, ENCAJE, P_RESPALDO, ESTADO, ID_USER, IP_USER, DATE_USER, COD_MONEDA)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 1000, 1000, 0, 0, 0, 'ACTIVO', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN');
INSERT INTO FINANCEBANK.T_BALANCEXMONEDA (IDBALANCE, ACTIVO_CAJAYBANCO, ACTIVO_CUENTAXCOBRAR, PASIVO, ENCAJE, P_RESPALDO, ESTADO, ID_USER, IP_USER, DATE_USER, COD_MONEDA)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 1000, 1000, 0, 0, 0, 'ACTIVO', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD');
INSERT INTO FINANCEBANK.T_BALANCEXMONEDA (IDBALANCE, ACTIVO_CAJAYBANCO, ACTIVO_CUENTAXCOBRAR, PASIVO, ENCAJE, P_RESPALDO, ESTADO, ID_USER, IP_USER, DATE_USER, COD_MONEDA)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 1000, 1000, 0, 0, 0, 'ACTIVO', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR');



INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.01', '001nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',10);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.05', '005nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',20);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.10', '010nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',30);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.20', '020nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',40);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.50', '050nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',50);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '1.00', '1nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',60);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '2.00', '2nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',70);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '5.00', '5nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',80);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '10.00', '10nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',90);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '20.00', '20nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',100);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '50.00', '50nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',110);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '100.00', '100nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',120);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '200.00', '200nuevosSoles.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'PEN',130);



INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.01', '001dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',10);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.05', '005dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',20);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.10', '010dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',30);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.25', '025dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',40);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.50', '050dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',50);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '1.00', '1dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',60);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '2.00', '2dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',70);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '5.00', '5dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',80);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '10.00', '10dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',90);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '20.00', '20dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',100);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '50.00', '50dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',110);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '100.00', '100dolares.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'USD',120);

INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.01', '001euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',10);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.02', '002euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',20);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.05', '005euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',30);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.10', '010euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',40);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.20', '020euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',50);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '0.50', '050euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',60);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '1.00', '1euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',70);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'MONEDA', '2.00', '2euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',80);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '5.00', '5euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',90);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '10.00', '10euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',100);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '20.00', '20euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',110);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '50.00', '50euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',120);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '100.00', '100euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',130);
INSERT INTO FINANCEBANK.T_DENOMINACION_MONEDA (IDDENOMINACIONMONEDA, TIPO, MONTO, IMAGEN, ID_USER, IP_USER, DATE_USER, COD_MONEDA, ORDEN)
	VALUES (to_char(systimestamp, 'yyyymmddhh24missFF'), 'BILLETE', '200.00', '200euro.jpg', 'ID_USER', 'IP_USER', 'DATE_USER', 'EUR',140);


/*

/* */
delete FINANCEBANK.T_PATRIMONIO;
delete FINANCEBANK.T_BALANCEXMONEDA;
delete FINANCEBANK.T_DETALLE_CAJA;
delete FINANCEBANK.T_TRANSFERENCIA_CAJA;